CREATE TABLE tb_as_25 (
  no INTEGER,
  no_spp TEXT,
  tgl_spp DATE,
  no_polisi TEXT,
  no_rangka TEXT,
  model TEXT,
  nama_pelanggan TEXT,
  "order" INTEGER,
  kelompok TEXT,
  sa TEXT,
  fo TEXT,
  teknisi TEXT,
  jam_masuk TEXT,
  otd TEXT,
  em TEXT,
  tunggu TEXT,
  tinggal TEXT,
  tms TEXT,
  kendtms TEXT,
  servisterakhir TEXT,
  program TEXT,
  teknisi_penyaransebelumnya TEXT,
  sumber_data_utilisasi TEXT,
  kontribusi_mra TEXT,
  kontribusi_effort TEXT,
  new_cust TEXT
);
