CREATE TABLE tb_ring (
  kode_pos TEXT,
  kelurahan TEXT,
  kecamatan TEXT,
  provinsi TEXT,
  kota TEXT,
  detail_alamat TEXT,
  latitude TEXT,
  longitude TEXT,
  bdg TEXT,
  kjr TEXT,
  tgr TEXT,
  kld TEXT,
  fwt TEXT,
  yos TEXT,
  pdg TEXT,
  pin TEXT,
  bks TEXT,
  kgd TEXT,
  kci TEXT,
  pdc TEXT,
  krw TEXT,
  cls TEXT,
  btg TEXT
);
