drop table if exists tb_utilisasi;
CREATE TABLE tb_utilisasi (
    no INT,
    nama_pelanggan VARCHAR(255),
    no_rangka VARCHAR(50),
    no_polisi VARCHAR(50),
    tahun_kendaraan INT,
    group_kendaraan VARCHAR(100),
    dealer_penjual VARCHAR(255),
    alamat_pelanggan TEXT,
    kode_pos VARCHAR(10),
    no_telp_pelanggan VARCHAR(250),
    no_hp_pelanggan VARCHAR(250),
    nama_pemakai VARCHAR(255),
    alamat_pemakai TEXT,
    no_telp_pemakai VARCHAR(250),
    nama_sa VARCHAR(100),
    kelompok_pekerjaan_terakhir VARCHAR(250),
    tgl_service_sebelumnya DATE,
    km_service_sebelumnya INT,
    tgl_next_service DATE,
    km_next_service INT,
    kategori_data VARCHAR(100),
    call_status VARCHAR(10),
    tanggal_follow_up DATE,
    connected VARCHAR(10),
    contacted VARCHAR(10),
    booking_on_call VARCHAR(10),
    call_result VARCHAR(255),
    remark TEXT,
    note TEXT,
    tgl_kedatangan DATE,
    status_cai VARCHAR(50),
    kelompok VARCHAR(50)
);
